services:
  oracle:
    extends:
      file: oracle/docker-compose.yaml
      service: oracle
  rabbitmq:
    extends:
      file: rabbitmq/docker-compose.yaml
      service: rabbitmq
  maildev:
    extends:
      file: maildev/docker-compose.yaml
      service: maildev
